# This file was generated by GoReleaser. DO NOT EDIT.
class Postmanctl < Formula
  desc ""
  homepage "https://github.com/kevinswiber/postmanctl"
  version "1.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kevinswiber/postmanctl/releases/download/1.1.4/postmanctl_1.1.4_Darwin_x86_64.tar.gz"
    sha256 "4215c394aae7a80b2def17b7da2c5f8cd04ad4fe34764dcc55fb793b196652b0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kevinswiber/postmanctl/releases/download/1.1.4/postmanctl_1.1.4_Linux_x86_64.tar.gz"
      sha256 "cccc9fe77aaba95fbd1bd8dabc717437c9cf2667233662cdb71617e1de7c18f6"
    end
  end
  
  head do
    url "https://github.com/kevinswiber/postmanctl.git"
    depends_on "go"
  end

  def install
    if head?
      system "go", "build", "./cmd/postmanctl"
    end
    
    bin.install "postmanctl"
  end
end
